"""cache ics feed text on IcsSource

Revision ID: 5c5161a38350
Revises: 76d4955e9751
Create Date: 2026-08-28 20:35:29.295750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5161a38350'
down_revision: Union[str, Sequence[str], None] = '76d4955e9751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ics_sources', sa.Column('cached_ics_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ics_sources', 'cached_ics_text')
    # ### end Alembic commands ###
