"""add channel to notifications

Revision ID: 6801037652f3
Revises: 5c5161a38350
Create Date: 2026-08-28 21:02:37.907602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6801037652f3'
down_revision: Union[str, Sequence[str], None] = '5c5161a38350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notifications',
        sa.Column('channel', sa.String(), nullable=False, server_default='reminder'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###
