"""add todo lists and items

Revision ID: 76d4955e9751
Revises: c1a9f3d7b2e4
Create Date: 2026-08-26 18:13:37.361312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d4955e9751'
down_revision: Union[str, Sequence[str], None] = 'c1a9f3d7b2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('caldav_url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('refresh_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('place_label', sa.String(), nullable=True),
    sa.Column('place_latitude', sa.Float(), nullable=True),
    sa.Column('place_longitude', sa.Float(), nullable=True),
    sa.Column('place_radius_m', sa.Integer(), nullable=True),
    sa.Column('place_inside', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dismissible', sa.Boolean(), nullable=False),
    sa.Column('snooze_minutes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_lists_user_id'), 'todo_lists', ['user_id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('todo_list_id', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['todo_list_id'], ['todo_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_list_id', 'uid', name='uq_todo_item_list_uid')
    )
    op.create_index(op.f('ix_todo_items_todo_list_id'), 'todo_items', ['todo_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_items_todo_list_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_todo_lists_user_id'), table_name='todo_lists')
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
