"""baseline schema

Matches the schema every deployment before this migration already has (it was previously
created ad hoc by `Base.metadata.create_all()` in `app/db.py::init_db`, with no migration
history at all). An existing production DB should be stamped at this revision rather than
have it actually run - see README.md's "Database migrations" section:

    alembic stamp 9bb7d0cbb5dd

A brand new install just runs `alembic upgrade head` normally, which executes this and every
migration after it in order.

Revision ID: 9bb7d0cbb5dd
Revises:
Create Date: 2026-08-09 14:12:42.764337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb7d0cbb5dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('weekdays_mask', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dismissible', sa.Boolean(), nullable=False),
    sa.Column('snooze_minutes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_schedules_user_id'), 'daily_schedules', ['user_id'], unique=False)
    op.create_table('ics_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('url_or_path', sa.String(), nullable=False),
    sa.Column('offsets_minutes', sa.JSON(), nullable=False),
    sa.Column('refresh_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dismissible', sa.Boolean(), nullable=False),
    sa.Column('snooze_minutes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ics_sources_user_id'), 'ics_sources', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dismissible', sa.Boolean(), nullable=False),
    sa.Column('snooze_minutes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('ack_action', sa.String(), nullable=True),
    sa.Column('ack_snoozed_minutes', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_dedupe_key')
    )
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ics_sources_user_id'), table_name='ics_sources')
    op.drop_table('ics_sources')
    op.drop_index(op.f('ix_daily_schedules_user_id'), table_name='daily_schedules')
    op.drop_table('daily_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
