"""add heart_rate_readings table

Revision ID: a425cf2a8e3b
Revises: e0827c75867b
Create Date: 2026-08-09 14:27:28.890469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a425cf2a8e3b'
down_revision: Union[str, Sequence[str], None] = 'e0827c75867b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_rate_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heart_rate_readings_recorded_at'), 'heart_rate_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_heart_rate_readings_user_id'), 'heart_rate_readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heart_rate_readings_user_id'), table_name='heart_rate_readings')
    op.drop_index(op.f('ix_heart_rate_readings_recorded_at'), table_name='heart_rate_readings')
    op.drop_table('heart_rate_readings')
    # ### end Alembic commands ###
