"""add delivered_at to notifications

Revision ID: e0827c75867b
Revises: 9bb7d0cbb5dd
Create Date: 2026-08-09 14:13:00.152659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0827c75867b'
down_revision: Union[str, Sequence[str], None] = '9bb7d0cbb5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'delivered_at')
    # ### end Alembic commands ###
